# Generated by Django 5.2.9 on 2025-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la materia')),
                ('comentario', models.TextField(verbose_name='Comentario del semestre')),
                ('semestre', models.CharField(max_length=20, verbose_name='Semestre')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
        ),
    ]
